name: test-build

on:
  push:
  pull_request:

jobs:
  gen-matrix:
    name: generate-matrix
    runs-on: ubuntu-latest

    steps:
      - name: Calculate file differences
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: diff
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate testing matrix
        uses: actions/github-script@v3
        id: generator
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/genMatrix.js`)
            return script(
              ${{ steps.diff.outputs.added }},
              ${{ steps.diff.outputs.modified }},
              ${{ steps.diff.outputs.renamed }},
            );

      - name: Matrix
        run: echo "${{ toJson(steps.generator.outputs.result) }}"

    outputs:
      matrix: ${{ steps.generator.outputs.result }}

  build:
    if: ${{ fromJson(needs.gen-matrix.outputs.matrix) }}
    needs: gen-matrix
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.gen-matrix.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Write experimental docker flag
        run: |
          echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json

      - name: Restart docker daemon
        run: sudo systemctl restart docker

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./${{ matrix.version }}/${{ matrix.variant }}/Dockerfile
          platforms: linux/${{ matrix.arch }}
          tags: node:${{ matrix.fullVersion }}-${{ matrix.variant }}

      - name: Test for node and version
        run: |
          image_node_version=$(docker run --platform linux/${{ matrix.arch }} --rm node:${{ matrix.fullVersion }}-${{ matrix.variant }} node -e "process.stdout.write(process.versions.node)")
          echo "Node | Expected: \"${{ matrix.fullVersion }}", Got: \"${image_node_version}\""
          [ "${image_node_version}" == "${{ matrix.fullVersion }}" ]

      - name: Test for npm
        run: docker run --platform linux/${{ matrix.arch }} --rmnode:${{ matrix.fullVersion }}-${{ matrix.variant }} npm --version

      - name: Test for yarn
        run: docker run --platform linux/${{ matrix.arch }} --rm node:${{ matrix.fullVersion }}-${{ matrix.variant }} yarn --version
