name: TARGET ONE

on:
  pull_request_target:
    types:
      - closed

jobs:
  pr:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'nodejs' && github.event.pull_request.merged_by != ''

    steps:
      - name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
