name: PUSH ONE

on:
  push:
    branches:
      - master

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
